<?php 
    $_products = $this->getProducts();
    $_config = $this->getConfig();
    $_columnWidth = 100 / $_config['limit'];
?>

<h2><?php echo __('Featured Products') ?></h2>

<ul class="products list items featured">
    <?php foreach ($_products as $_product): ?>
        <li class="item" style="width: <?php echo $_columnWidth; ?>%">
            <div class="product">
                <a href="<?php echo $_product->getProductUrl() ?>" class="product photo product-item-photo">
                    <img src="<?php echo $this->getImageHelper()->init($_product, 'image')->resize($_config['image_width']); ?>" alt="<?php echo $this->escapeHtml($_product->getName()) ?>" />
                    <span class="product-item-name"><?php echo $this->escapeHtml($_product->getName()) ?></span>
                </a>
                <?php echo $this->getProductPrice($_product) ?>
            </div>
        </li>
    <?php endforeach; ?>
</ul>

